using System.Text.Json.Nodes;

namespace R3P.Hivemind.Core.Interop;

/// <summary>
/// Represents a logical command sent to the plug-in. Requests are intentionally
/// lightweight JSON documents so they can be routed through a variety of transports
/// and consumed by native or managed components alike.
/// </summary>
/// <param name="Command">The conduit command to execute.</param>
/// <param name="Payload">Optional JSON payload associated with the command.</param>
/// <param name="CorrelationId">Optional correlation identifier supplied by the caller.</param>
public sealed record IpcRequest(
    string Command,
    JsonObject? Payload,
    string? CorrelationId)
{
    /// <summary>
    /// Creates a request without a payload. The correlation identifier is generated by the
    /// transport when not explicitly supplied.
    /// </summary>
    public IpcRequest(string command)
        : this(command, null, null)
    {
    }

    /// <summary>
    /// Creates a request with a payload but without a correlation identifier.
    /// </summary>
    public IpcRequest(string command, JsonObject payload)
        : this(command, payload, null)
    {
    }
}
